name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-14

    env:
      TEST: 1

    steps:
      - uses: actions/checkout@v5

      - name: Create GoogleService-Info.plist from GOOGLE_SERVICE_INFO_PLIST
        run: |
          echo GOOGLE_SERVICE_INFO_PLIST | base64 -d >> Tests/GoogleService-Info.plist
        shell: bash
        env:
          GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}

      - name: Change Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test